spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/delivery
    username: pavelkaranda
    password: bestuser
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  session:
    store-type: jdbc

  ldap:
    urls: ldap://192.168.30.10:3268/
    base: DC=itfbgroup,DC=local
    username: portal_user@itfbgroup.local
    password: Q1w2e3r4
    user-search-filter: (&(objectClass=user)(sAMAccountName={0}))
    user-uid: sAMAccountName
    referral: ignore
    attrs:
      - sAMAccountName
      - mail
      - displayName
      - memberOf
      - userAccountControl
server:
  servlet:
    context-path: /food-delivery-service

logging:
  level:
    org:
      springframework:
        security: DEBUG

app:
  integration:
    payment:
      url: http://localhost:8081/payment-service
    courier:
      url: http://localhost:8082/courier-service