spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/delivery
    username: pavelkaranda
    password: bestuser
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
